# ================================ 
# Slavopolis Gateway 网关服务配置
# ================================ 

# 服务基础配置
spring:
  application:
    name: slavopolis-gateway
  profiles:
    active: dev
  
  # Jackson JSON配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# 服务端口配置
server:
  port: 8080

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true 