# Slavopolis JDBC 默认配置
# 其他业务模块引入此模块后将自动获得这些通用配置
slavopolis:
  jdbc:
    #====================================  基础配置 ====================================
    # 是否启用增强JDBC功能
    enabled: true
    # 默认启用日志
    default-logging-enabled: true
    # 默认分页大小
    default-page-size: 20
    # 最大分页大小
    max-page-size: 1000
    
    #====================================  监控配置  ====================================
    monitor:
      # 是否启用SQL执行监控
      enabled: true
      # 慢查询阈值（毫秒）
      slow-query-threshold: 1000
      # 是否启用统计信息收集
      statistics-enabled: true
      # 统计信息清理间隔（支持时间单位：1h, 30m, 60s等）
      statistics-cleanup-interval: 1h
      # 最大统计条目数
      max-statistics-entries: 10000

    #====================================  安全配置  ====================================
    security:
      # ========== JdbcProperties.Security 配置 ==========
      # 是否启用SQL注入检测
      sql-injection-detection-enabled: true
      # 是否启用参数验证
      parameter-validation-enabled: true
      # 危险关键词列表（JdbcProperties中定义）
      dangerous-keywords:
        - "DROP"
        - "DELETE"
        - "TRUNCATE"
        - "ALTER"
        - "CREATE"
        - "INSERT"
        - "UPDATE"
        - "GRANT"
        - "REVOKE"
        - "EXEC"
        - "EXECUTE"
        - "UNION"
        - "SCRIPT"
        - "JAVASCRIPT"
        - "VBSCRIPT"
        - "ONLOAD"
        - "ONERROR"
      # 是否启用敏感表访问控制
      sensitive-table-control-enabled: false
      # 敏感表名列表
      sensitive-tables:
        - "user"
        - "password"
        - "credential"
        - "token"
        - "session"
      
      # ========== SqlSecurityConfig 专用配置 ==========
      # 是否启用SQL安全检查（总开关）
      enabled: true
      # 是否启用SQL注入检测（SqlSecurityConfig版本）
      sql-injection-detection: true
      # 是否启用参数验证（SqlSecurityConfig版本）
      parameter-validation: true
      # 是否启用敏感信息掩码
      sensitive-data-masking: true
      # 敏感参数名称模式
      sensitive-parameter-patterns:
        - "password"
        - "pwd"
        - "secret"
        - "token"
        - "key"
        - "auth"
      # 最大参数值长度
      max-parameter-length: 10000
      # 最大批处理大小
      max-batch-size: 1000
      # 是否允许DDL操作
      allow-ddl-operations: false
      # 是否允许无WHERE子句的UPDATE/DELETE
      allow-unsafe-operations: false
      # SQL长度限制
      max-sql-length: 50000
      # 是否记录安全警告
      log-security-warnings: true
        
    #====================================  事务配置  ====================================
    transaction:
      # 默认事务传播行为（REQUIRED, REQUIRES_NEW, SUPPORTS, NOT_SUPPORTED, MANDATORY, NEVER, NESTED）
      propagation: REQUIRED
      # 默认事务隔离级别（DEFAULT, READ_UNCOMMITTED, READ_COMMITTED, REPEATABLE_READ, SERIALIZABLE）
      isolation: DEFAULT
      # 默认事务超时时间（秒）
      timeout: 30
      # 是否只读事务
      read-only: false
      # 回滚异常类名列表
      rollback-for:
        - "java.lang.Exception"
        
    #====================================  映射配置  ====================================
    mapping:
      # 默认映射策略（INTELLIGENT, STRICT, LENIENT）
      default-strategy: INTELLIGENT
      # 是否启用映射缓存
      cache-enabled: true
      # 映射缓存最大条目数
      max-cache-entries: 1000
      # 是否检查完整映射（检查所有属性是否都被映射）
      check-fully-populated: false
      # 原始类型是否默认为null值（当数据库字段为null时，int等原始类型是否设为null而非0）
      primitives-defaulted-for-null-value: false
      # 下划线转驼峰映射（数据库字段user_name自动映射到Java属性userName）
      underscore-to-camel-case: true 