# slavopolis-excel 配置文件模板
slavopolis:
  excel:
    # 是否启用Excel功能
    enabled: true
    
    # 验证配置
    validation:
      # 最大文件大小（字节）
      max-file-size: 52428800  # 50MB
      # 最大行数
      max-rows: 100000
      # 最大列数
      max-columns: 256
      # 允许的文件扩展名
      allowed-extensions:
        - xlsx
        - xls
        - csv
    
    # 异步处理配置
    async:
      # 文件大小阈值（超过此大小将使用异步处理）
      file-size-threshold: 10485760  # 10MB
      # 线程池配置
      thread-pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        keep-alive: 60
        name-prefix: "excel-async-"
    
    # 性能配置
    performance:
      # 默认批次大小
      default-batch-size: 1000
      # 内存优化阈值
      memory-threshold: 5000
      # 是否启用缓存
      enable-cache: true
      # 缓存过期时间（秒）
      cache-expire-seconds: 3600
    
    # 错误处理配置
    error:
      # 是否快速失败
      fail-fast: false
      # 最大错误数量
      max-errors: 100
      # 是否收集详细错误信息
      collect-detail: true
    
    # 注解处理配置
    annotation:
      # 是否启用注解处理
      enabled: true
      # 是否启用元数据缓存
      cache-enabled: true
      # 缓存大小
      cache-size: 500
    
    # 监控配置
    monitoring:
      # 是否启用监控
      enabled: true
      # 是否启用性能统计
      performance-stats: true
      # 是否启用JVM监控
      jvm-monitoring: true
    
    # 模板配置
    template:
      # 模板文件根路径
      base-path: "classpath:excel/templates/"
      # 是否启用模板缓存
      cache-enabled: true
      # 缓存大小
      cache-size: 100
      # 模板文件扫描路径
      scan-packages:
        - "**.excel.template" 