# ================================ 
# 开发环境配置 - Slavopolis Auth
# ================================ 

# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/slavopolis_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    
    # Druid连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: club.slavopolis.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    root: INFO
    club.slavopolis.auth: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  file:
    name: logs/slavopolis-auth-dev.log

# Slavopolis 自定义配置
slavopolis:
  # 安全配置
  security:
    # JWT配置
    jwt:
      secret: slavopolis-jwt-secret-key-2025
      expiration: 7200000
      refresh-expiration: 604800000
    # 验证码配置
    captcha:
      sms:
        length: 6
        expiration: 300
        daily-limit: 10
      email:
        length: 6
        expiration: 300
        daily-limit: 10 